---
title: "How to use Evitlas"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How_to_use_Evitlas}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
conflictRules("tidyr", mask.ok = c("extract"))
conflictRules("dplyr", mask.ok = c("filter", "lag", "select"))
pacman::p_load(devtools,dplyr,tidyverse)
```

```{r}
metadata <- read_csv(here::here("inst","extdata","metadata.csv")) %>% filter(!is.na(Longitude))
bounds <- read_rds(here::here("inst","extdata","wb_bounds.rds")) %>%
  filter((SM.POP.REFG>100000 | idp_n>1000000) & income_group!="High income") %>%
  dplyr::select(ISO_A3,NAME_EN)

list_inc <- bounds %>% 
  st_drop_geometry() %>%
  select(ISO_A3) %>% 
  as.vector(.)

#bounds <- read_rds(here::here("inst","extdata","UNHCR_bounds.rds")) %>%
#  select(ISO_A3=Country_te)
ref_data <- read_rds(here::here("inst","extdata","wb_bounds_stats.rds")) %>%
  #filter(!is.na(value)) %>%
  filter(ISO_A3 %in% list_inc$ISO_A3)
#get the centroid of those countries
bounds$geom_valid <- st_is_valid(bounds)

##show list of countries with invalid geometries
bounds <- bounds %>% filter(geom_valid=="TRUE") 
table(bounds$geom_valid)

usethis::use_data(metadata, bounds, ref_data, overwrite=TRUE)
```
