---
title: "How to use FDPDataAtlas"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How_to_use_FDPDataAtlas}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
conflictRules("tidyr", mask.ok = c("extract"))
conflictRules("dplyr", mask.ok = c("filter", "lag", "select"))
pacman::p_load(devtools,dplyr,tidyverse,sf,here, devtools)
```
If any update has been made in the metadata, run this chunk. 
```{r, echo=FALSE, eval=FALSE}
metadata <- read_csv(here::here("inst","extdata","metadata_v2.csv")) %>% 
  filter(!is.na(Longitude)) %>%
  dplyr::select(-database,-method_research_instrument,-cit_req,-disclaimer,-Region_v2,-Economy)
bounds <- read_rds(here::here("inst","extdata","wb_bounds.rds")) 
bounds %>%
  st_drop_geometry() %>%
  write_csv(here::here("inst","extdata","wb_bounds.csv"))
list_inc <- bounds %>% 
  st_drop_geometry() %>%
  select(ISO_A3) %>% 
  as.vector(.)

#bounds <- read_rds(here::here("inst","extdata","UNHCR_bounds.rds")) %>%
#  select(ISO_A3=Country_te)

list_drop <- c("asy_ven","NY.GDP.PCAP.CD","ref_ven","SL.UEM.TOTL.ZS","SP.POP.TOTL")
ref_data <- read_rds(here::here("inst","extdata","wb_bounds_stats.rds")) %>%
  #filter(!is.na(value)) %>%
  filter(!indicator %in% list_drop) %>%
  filter(ISO_A3 %in% list_inc$ISO_A3)
#get the centroid of those countries
bounds$geom_valid <- st_is_valid(bounds)

##show list of countries with invalid geometries
bounds <- bounds %>% 
  filter(geom_valid=="TRUE") 

##relabel some of the indicators 
ref_data <- ref_data %>%
  mutate(indicator=ifelse(indicator=="Refugee population by country or territory of asylum (2021) (WDI)","Refugee population by country or territory of asylum (2021) (UNHCR Refugee Data Finder)",indicator)) %>%
   mutate(indicator=ifelse(indicator=="Refugee population by country or territory of origin (2021) (WDI)","Refugee population by country or territory of origin (2021) (UNHCR Refugee Data Finder)", indicator)) 
table(ref_data$indicator)

##read data dictionary
datadictionary <- read_csv(here::here("inst","extdata","datadictionary.csv"))

usethis::use_data(metadata, bounds, ref_data, datadictionary, overwrite=TRUE)
```
if any update has been made to the package, run this chunk and test.
```{r, echo=FALSE, eval=FALSE}
library(devtools)
document()
load_all()
runShiny()
```

Lastly, launch the app but make sure that you first install FDPDataAtlas through install_github("takaakimasaki/FDPDataAtlas") otherwise it returns an error. 

To install FDPDataAtlas afresh from GitHub, you need to restart your RStudio.
```{r}
remotes::install_github("takaakimasaki/FDPDataAtlas") 
library(FDPDataAtlas)
runShiny()
```